url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "RemoSIM" # the name of your site, e.g. ACME Corp.
description: "Roam free Simcard Calls and Texts"
markdown: kramdown